backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: static/images/uploads
public_folder: /images/uploads
collections:
  - name: glossary
    label: Glossary
    folder: content/glossary
    create: true
    filter: {field: entry, value: true}
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Definition, name: definition, widget: markdown}
      - {label: Identifier, name: slug, widget: string}
      - {label: IsEntry, name: entry, widget: hidden, default: true}
